name: okoskert_internal
description: "An internal app for Okoskert"
publish_to: 'none'
version: 0.1.12

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  flutter_expandable_fab: ^2.5.2
  maps_launcher: ^3.0.0+1
  url_launcher: ^6.3.2
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  insta_image_viewer: ^1.0.4
  cached_network_image: ^3.4.1
  table_calendar: ^3.2.0
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
